version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Pre-build
          command: npm install
      - run:
          name: Run Unit Tests
          command: npm run test
      - run:
          name: Pre-deploy
          command: npm run build
      - run:
          name: Deploy
          command: npm run deploy
      - run:
          name: Run Functional Tests
          command: echo "functional tests"
