version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - run:
          name: Checkout
          command: echo "pulling the lastest code"
      - run:
          name: Build
          command: echo "build"
      - run:
          name: Run Unit Tests
          command: echo "unit tests"
      - run:
          name: Deploy
          command: echo "deploy to host"
      - run:
          name: Run Functional Tests
          command: echo "functional tests"
